### ISSUE TITLE
How to use for WGS data

### ISSUE THREAD

**Issue by praveenraj2018** [bioinfo-pf-curie/TMB#13]
Very nice to see a tool with a comprehensive list of parameters!!

I am a little unclear on how to use this for whole-genome data. Should we use `--effGenomeSize` or `--bed` file or both? What do you recommend and a typical example usage from your validation experiments? This would be very useful to know and if possible include it in the documentation.

thanks!

**Comment by tomgutman** [comment]
Hello,

This tool was primarily developed and tested for WES and panels. We have never used it for WGS. But it is totally usable for this type of data. 
I would advise to use `--effGenomeSize` with the size of the reference genome used.
For the parameters I would advise to include coding, non coding and splicing variants. 

I hope it helps

Tom

**Comment by nservant** [comment]
Hi, so far, this is up to you to calcule the effective genome size, in accordance to the filters you applied. So indeed, if you are using a WGS and use only coding regions, it makes sense to exclude the non-coding regions from the genomic size.  
But so far, this is not done by `pyTMB` itself
N
