### ISSUE TITLE
Is  the VEP annotated vcf supported?

### ISSUE THREAD

**Issue by gudeqing** [bioinfo-pf-curie/TMB#8]
Hi,
Is  the VEP annotated vcf supported?
Best regards!

**Comment by nservant** [comment]
Hi,
Not yet, but you should be able to do it by yourself, by setting up your own config file for VEP.
See the files in config/annovar.yml for exemple.
The only thing you have to do is defined the different categories; coding, non coding, etc.
If you do it, I'll be happy to include it in the repo ;)
Thanks
